services:
  soarca-ui-react:
    image: soarca-ui-react:latest
    build:
      context: .
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
