services:
  soarca-ui-react:
    image: soarca-ui-react:development
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    command: sh -c "npm install && npm run dev"

volumes:
  node_modules_volume:
