// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func HeaderBar() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<header class=\"w-full items-center bg-slate-50 py-2 px-6 hidden sm:flex\"><div class=\"w-1/2\"></div><div x-data=\"{ isOpen: false }\" class=\"relative w-1/2 flex justify-end\"><button @click=\"isOpen = !isOpen\" class=\"realtive z-10 w-12 h-12 rounded-full overflow-hidden border-4 border-gray-400 hover:border-blue-600 focus:border-blue-600 focus:outline-none\"><img src=\"https://source.unsplash.com/uJ8LNVCBjFQ/400x400\"></button> <button x-show=\"isOpen\" @click=\"isOpen = false\" class=\"h-full w-full fixed inset-0 cursor-default\"></button><div x-show=\"isOpen\" class=\"absolute w-32 bg-white rounded-lg shadow-lg py-2 mt-16 z-50\"><a href=\"#\" class=\"block px-4 py-2 account-link hover:text-blue-600\">Account</a> <a href=\"#\" class=\"block px-4 py-2 account-link hover:text-blue-600\">Settings</a> <a href=\"#\" class=\"block px-4 py-2 account-link hover:text-blue-600\">Sign Out</a></div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
